### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LumerGD120** [hiimjustin000/BetterSafe#2]
Crashes when u press one of the difficulty faces

The crash dmp:
[Crash 2024-09-14 08.51.56.dmp](https://github.com/user-attachments/files/17000394/Crash.2024-09-14.08.51.56.dmp)
The video proof:

https://github.com/user-attachments/assets/d517a755-9b54-4c90-b177-2695991ad51a

**Comment by hiimjustin000** [comment]
Fixed in v1.0.3 (a71f1b6)
