### ISSUE TITLE
Reload Button Broke

### ISSUE THREAD

**Issue by nbieberitz** [hiimjustin000/BetterSafe#5]
Everything loads properly in the better safe, but as soon as I hit the reload button, it loads and loads and loads, but nothing happens.

![Screenshot_20241120_182754_Geode](https://github.com/user-attachments/assets/73deff0b-fa68-4faa-a4f3-bb8747276159)

**Comment by hiimjustin000** [comment]
strange

**Comment by nbieberitz** [comment]
Yeah

**Comment by nbieberitz** [comment]
Video evidence:


https://github.com/user-attachments/assets/44f35982-6453-40f7-a01b-58636794beae
